// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOZ66ODewx9unRbkOpg3KBrpZZtg533s',
    appId: '1:873559957687:android:9d8e2aa06628ea98fb2d32',
    messagingSenderId: '873559957687',
    projectId: 'clinixai-9bb6d',
    storageBucket: 'clinixai-9bb6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXaqGVkXcviXFV9gCgLKJPlyNe571dJk',
    appId: '1:873559957687:ios:30ad3e4a197c166afb2d32',
    messagingSenderId: '873559957687',
    projectId: 'clinixai-9bb6d',
    storageBucket: 'clinixai-9bb6d.firebasestorage.app',
    androidClientId: '873559957687-2lv7iopp6n2ll5alkmfo7qvrtr3ih62v.apps.googleusercontent.com',
    iosClientId: '873559957687-emljucvb770bsvosgcbq81bajcbmfn7l.apps.googleusercontent.com',
    iosBundleId: 'com.sisirlabs.clinixai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXaqGVkXcviXFV9gCgLKJPlyNe571dJk',
    appId: '1:873559957687:ios:30ad3e4a197c166afb2d32',
    messagingSenderId: '873559957687',
    projectId: 'clinixai-9bb6d',
    storageBucket: 'clinixai-9bb6d.firebasestorage.app',
    androidClientId: '873559957687-2lv7iopp6n2ll5alkmfo7qvrtr3ih62v.apps.googleusercontent.com',
    iosClientId: '873559957687-emljucvb770bsvosgcbq81bajcbmfn7l.apps.googleusercontent.com',
    iosBundleId: 'com.sisirlabs.clinixai',
  );

}