// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvuqZR53caxlhm2rGUj0Z2K6zC_I4tYi8',
    appId: '1:424092846196:android:47c401e2af11178b7ba921',
    messagingSenderId: '424092846196',
    projectId: 'docpilot-b93fb',
    storageBucket: 'docpilot-b93fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_kHP9omacDeb7kXIuZ9OLFxWVtaNZVg',
    appId: '1:424092846196:ios:16f0b368a68c09237ba921',
    messagingSenderId: '424092846196',
    projectId: 'docpilot-b93fb',
    storageBucket: 'docpilot-b93fb.firebasestorage.app',
    androidClientId: '424092846196-dv59nv3i5klnh3cqcvgkllatc30afs1k.apps.googleusercontent.com',
    iosClientId: '424092846196-on6s0hhbpbblh2s7st2obkbo2hv6v504.apps.googleusercontent.com',
    iosBundleId: 'com.sisir.docpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_kHP9omacDeb7kXIuZ9OLFxWVtaNZVg',
    appId: '1:424092846196:ios:16f0b368a68c09237ba921',
    messagingSenderId: '424092846196',
    projectId: 'docpilot-b93fb',
    storageBucket: 'docpilot-b93fb.firebasestorage.app',
    androidClientId: '424092846196-dv59nv3i5klnh3cqcvgkllatc30afs1k.apps.googleusercontent.com',
    iosClientId: '424092846196-on6s0hhbpbblh2s7st2obkbo2hv6v504.apps.googleusercontent.com',
    iosBundleId: 'com.sisir.docpilot',
  );

}